[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

# Add this section if you have a binary
[[bin]]
name = "websocket"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.40", features = ["full"] } 
tokio-tungstenite = "0.16"
futures-util = "0.3.14"