# Configuration for Cross-Entropy Method (CEM) algorithm

# Algorithm hyperparameters
num_iterations: 10       # Number of iterations for the CEM algorithm
population_size: 50      # Size of the population for each iteration
top_percent: 0.2         # Percentage of top-performing individuals to select
sample_episodes: 5       # Number of episodes to evaluate each individual
initial_std: 0.1         # Initial standard deviation for parameter perturbations

# Network settings
policy_lr: 0.001         # Learning rate for the policy network

# Training settings
max_episodes: 1000       # Maximum number of episodes for training
max_steps_per_episode: 500  # Maximum number of steps per episode

# Logging and saving
log_interval: 10         # Interval for logging training progress
save_interval: 100       # Interval for saving the model

# Device settings
device: "cuda"           # Use "cuda" for GPU, "cpu" for CPU

# Evaluation settings
eval_episodes: 10        # Number of episodes for evaluation
